// blob.hpp — width-typed Blob persistence wrappers.
//
// Three move-only RAII wrappers — `Blob128` / `Blob256` / `Blob512`
// — pack the low-level encryptor material plus captured globals
// into one self-describing JSON blob. Each wraps the corresponding
// C-binding opaque handle (`itb_blob128_t` / `itb_blob256_t` /
// `itb_blob512_t`).
//
// Slot constants exposed as `itb::blob::Slot` for type-safer lookup
// than raw int literals; bitwise option flags as `itb::blob::Opt`.
//
// Imports raise the three Blob-specific exception classes —
// `ItbBlobModeMismatchError`, `ItbBlobMalformedError`,
// `ItbBlobVersionTooNewError` — for the corresponding STATUS_BLOB_*
// codes, all derived from `ItbError` so callers can catch the base
// class generically.
//
// The three width-typed classes share an identical public surface;
// the only difference between them is which `itb_blob<W>_*` C ABI
// entry point each method forwards to. The class definitions are
// generated by a single macro expansion so the parallel implementations
// stay in lock-step automatically.

#pragma once

#include <itb.h>
#include <itb/encryptor.hpp>  // for detail::consume_buffer + detail::read_two_call_string
#include <itb/errors.hpp>

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace itb {
namespace blob {

// Slot identifiers — mirror `BlobSlot*` in the C ABI header.
enum class Slot : int {
    Noise   = 0,  // shared: noiseSeed + KeyN
    Data    = 1,  // Single: dataSeed + KeyD
    Start   = 2,  // Single: startSeed + KeyS
    Lock    = 3,  // optional any mode: dedicated lockSeed
    Data1   = 4,  // Triple: dataSeed1 + KeyD1
    Data2   = 5,
    Data3   = 6,
    Start1  = 7,  // Triple: startSeed1 + KeyS1
    Start2  = 8,
    Start3  = 9,
};

inline int to_int(Slot s) noexcept { return static_cast<int>(s); }

// Export option flags. Combine with bitwise OR; pass the OR-result
// as the `opts` parameter to `export_blob` / `export_triple`.
enum Opt : int {
    None      = 0,
    LockSeed  = ITB_BLOB_OPT_LOCKSEED,
    Mac       = ITB_BLOB_OPT_MAC,
};

} // namespace blob

// The macro expands to a complete class definition for one width.
// `W` is the width literal (128 / 256 / 512); `T` is the
// corresponding C-binding opaque handle type.
#define ITB_DEFINE_BLOB_CPP(W, T)                                              \
class Blob##W {                                                                \
public:                                                                        \
    Blob##W() {                                                                \
        int rc = itb_blob##W##_new(&handle_);                                  \
        if (rc != ITB_OK) {                                                    \
            handle_ = nullptr;                                                 \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
    }                                                                          \
                                                                               \
    Blob##W(const Blob##W&) = delete;                                          \
    Blob##W& operator=(const Blob##W&) = delete;                               \
                                                                               \
    Blob##W(Blob##W&& other) noexcept : handle_{other.handle_} {               \
        other.handle_ = nullptr;                                               \
    }                                                                          \
                                                                               \
    Blob##W& operator=(Blob##W&& other) noexcept {                             \
        if (this != &other) {                                                  \
            release();                                                         \
            handle_ = other.handle_;                                           \
            other.handle_ = nullptr;                                           \
        }                                                                      \
        return *this;                                                          \
    }                                                                          \
                                                                               \
    ~Blob##W() noexcept { release(); }                                         \
                                                                               \
    T* raw_handle() const noexcept { return handle_; }                         \
                                                                               \
    int width() const {                                                        \
        int v = 0;                                                             \
        detail::check(itb_blob##W##_width(handle_, &v));                       \
        return v;                                                              \
    }                                                                          \
    int mode() const {                                                         \
        int v = 0;                                                             \
        detail::check(itb_blob##W##_mode(handle_, &v));                        \
        return v;                                                              \
    }                                                                          \
                                                                               \
    void set_key(blob::Slot slot, const std::vector<std::uint8_t>& key) {      \
        const std::uint8_t* p = key.empty() ? nullptr : key.data();            \
        detail::check(itb_blob##W##_set_key(                                   \
            handle_, blob::to_int(slot), p, key.size()));                      \
    }                                                                          \
                                                                               \
    std::vector<std::uint8_t> get_key(blob::Slot slot) const {                 \
        std::size_t cap = 0;                                                   \
        int rc = itb_blob##W##_get_key(                                        \
            handle_, blob::to_int(slot), nullptr, 0, &cap);                    \
        if (rc != ITB_OK && rc != ITB_BUFFER_TOO_SMALL) {                      \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
        if (cap == 0) {                                                        \
            return {};                                                         \
        }                                                                      \
        std::vector<std::uint8_t> out(cap);                                    \
        std::size_t got = 0;                                                   \
        detail::check(itb_blob##W##_get_key(                                   \
            handle_, blob::to_int(slot), out.data(), cap, &got));              \
        out.resize(got);                                                       \
        return out;                                                            \
    }                                                                          \
                                                                               \
    void set_components(blob::Slot slot,                                       \
                        const std::vector<std::uint64_t>& comps) {             \
        const std::uint64_t* p = comps.empty() ? nullptr : comps.data();       \
        detail::check(itb_blob##W##_set_components(                            \
            handle_, blob::to_int(slot), p, comps.size()));                    \
    }                                                                          \
                                                                               \
    std::vector<std::uint64_t> get_components(blob::Slot slot) const {         \
        std::size_t cap = 0;                                                   \
        int rc = itb_blob##W##_get_components(                                 \
            handle_, blob::to_int(slot), nullptr, 0, &cap);                    \
        if (rc != ITB_OK && rc != ITB_BUFFER_TOO_SMALL) {                      \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
        if (cap == 0) {                                                        \
            return {};                                                         \
        }                                                                      \
        std::vector<std::uint64_t> out(cap);                                   \
        std::size_t got = 0;                                                   \
        detail::check(itb_blob##W##_get_components(                            \
            handle_, blob::to_int(slot), out.data(), cap, &got));              \
        out.resize(got);                                                       \
        return out;                                                            \
    }                                                                          \
                                                                               \
    void set_mac_key(const std::vector<std::uint8_t>& key) {                   \
        const std::uint8_t* p = key.empty() ? nullptr : key.data();            \
        detail::check(itb_blob##W##_set_mac_key(handle_, p, key.size()));      \
    }                                                                          \
                                                                               \
    std::vector<std::uint8_t> get_mac_key() const {                            \
        std::size_t cap = 0;                                                   \
        int rc = itb_blob##W##_get_mac_key(handle_, nullptr, 0, &cap);         \
        if (rc != ITB_OK && rc != ITB_BUFFER_TOO_SMALL) {                      \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
        if (cap == 0) {                                                        \
            return {};                                                         \
        }                                                                      \
        std::vector<std::uint8_t> out(cap);                                    \
        std::size_t got = 0;                                                   \
        detail::check(itb_blob##W##_get_mac_key(                               \
            handle_, out.data(), cap, &got));                                  \
        out.resize(got);                                                       \
        return out;                                                            \
    }                                                                          \
                                                                               \
    void set_mac_name(std::string_view name) {                                 \
        std::string nul_terminated{name};                                      \
        const char* p = name.empty() ? nullptr : nul_terminated.c_str();       \
        detail::check(itb_blob##W##_set_mac_name(handle_, p));                 \
    }                                                                          \
                                                                               \
    std::string get_mac_name() const {                                         \
        T* h = handle_;                                                        \
        return detail::read_two_call_string(                                   \
            [h](char* buf, std::size_t cap, std::size_t* out_len) {            \
                return itb_blob##W##_get_mac_name(h, buf, cap, out_len);       \
            });                                                                \
    }                                                                          \
                                                                               \
    std::vector<std::uint8_t> export_blob(int opts = blob::None) const {       \
        std::uint8_t* buf = nullptr;                                           \
        std::size_t len = 0;                                                   \
        int rc = itb_blob##W##_export(handle_, opts, &buf, &len);              \
        if (rc != ITB_OK) {                                                    \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
        return detail::consume_buffer(buf, len);                               \
    }                                                                          \
                                                                               \
    std::vector<std::uint8_t> export_triple(int opts = blob::None) const {     \
        std::uint8_t* buf = nullptr;                                           \
        std::size_t len = 0;                                                   \
        int rc = itb_blob##W##_export3(handle_, opts, &buf, &len);             \
        if (rc != ITB_OK) {                                                    \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
        return detail::consume_buffer(buf, len);                               \
    }                                                                          \
                                                                               \
    void import_blob(const std::uint8_t* blob, std::size_t len) {              \
        int rc = itb_blob##W##_import(handle_, blob, len);                     \
        if (rc != ITB_OK) {                                                    \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
    }                                                                          \
                                                                               \
    void import_blob(const std::vector<std::uint8_t>& blob) {                  \
        import_blob(blob.data(), blob.size());                                 \
    }                                                                          \
                                                                               \
    void import_triple(const std::uint8_t* blob, std::size_t len) {            \
        int rc = itb_blob##W##_import3(handle_, blob, len);                    \
        if (rc != ITB_OK) {                                                    \
            detail::throw_from_status(rc);                                     \
        }                                                                      \
    }                                                                          \
                                                                               \
    void import_triple(const std::vector<std::uint8_t>& blob) {                \
        import_triple(blob.data(), blob.size());                               \
    }                                                                          \
                                                                               \
private:                                                                       \
    void release() noexcept {                                                  \
        if (handle_ != nullptr) {                                              \
            itb_blob##W##_free(handle_);                                       \
            handle_ = nullptr;                                                 \
        }                                                                      \
    }                                                                          \
                                                                               \
    T* handle_ = nullptr;                                                      \
}

ITB_DEFINE_BLOB_CPP(128, itb_blob128_t);
ITB_DEFINE_BLOB_CPP(256, itb_blob256_t);
ITB_DEFINE_BLOB_CPP(512, itb_blob512_t);

#undef ITB_DEFINE_BLOB_CPP

} // namespace itb
